version: '3.8'

services:
  babelon:
    build: .
    container_name: babelon
    env_file:
      - .env
    volumes:
      - .:/mnt
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stdin_open: true
    tty: true
    command: /bin/bash