"""rename_recording_id_to_task_id

Revision ID: 4f61bbe52f6a
Revises: beeeea1b9c7f
Create Date: 2025-12-12 13:57:09.740029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f61bbe52f6a'
down_revision: Union[str, Sequence[str], None] = 'beeeea1b9c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('babelon_service_Babelon_whisper_API', sa.Column('task_id', sa.String(length=100), nullable=True))
    op.drop_column('babelon_service_Babelon_whisper_API', 'recording_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('babelon_service_Babelon_whisper_API', sa.Column('recording_id', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('babelon_service_Babelon_whisper_API', 'task_id')
    # ### end Alembic commands ###
