"""remove_speaker_fields_and_add_prev_text

Revision ID: a0786ca0e0b5
Revises: b36c1f5cc88d
Create Date: 2025-12-12 11:24:07.096457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0786ca0e0b5'
down_revision: Union[str, Sequence[str], None] = 'b36c1f5cc88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('babelon_service_Babelon_whisper_API', sa.Column('prev_text', sa.UnicodeText(), nullable=True))
    op.drop_column('babelon_service_Babelon_whisper_API', 'audio_info')
    op.drop_column('babelon_service_Babelon_whisper_API', 'speaker_id')
    op.drop_column('babelon_service_Babelon_whisper_API', 'speaker_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('babelon_service_Babelon_whisper_API', sa.Column('speaker_name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('babelon_service_Babelon_whisper_API', sa.Column('speaker_id', sa.VARCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('babelon_service_Babelon_whisper_API', sa.Column('audio_info', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.drop_column('babelon_service_Babelon_whisper_API', 'prev_text')
    # ### end Alembic commands ###
