"""init table

Revision ID: b36c1f5cc88d
Revises: 
Create Date: 2025-11-11 02:29:52.301004

"""
from typing import Sequence, Union

from alembic import op, context
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b36c1f5cc88d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    table_prefix = context.config.attributes.get("prefix", "mycopilot")
    if not table_prefix.endswith("_"):
        table_prefix += "_"
        
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(f'{table_prefix}Babelon_whisper_API',
    sa.Column('meeting_id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('recording_id', sa.String(length=100), nullable=True),
    sa.Column('speaker_id', sa.String(length=32), nullable=False),
    sa.Column('speaker_name', sa.String(length=100), nullable=True),
    sa.Column('audio_id', sa.String(length=32), nullable=False),
    sa.Column('audio_frame_timestamp', sa.DateTime(), nullable=False),
    sa.Column('audio_file_name', sa.String(length=300), nullable=False),
    sa.Column('source_lang', sa.String(length=100), nullable=False),
    sa.Column('transcription_text', sa.UnicodeText(), nullable=True),
    sa.Column('translation', sa.UnicodeText(), nullable=False),
    sa.Column('transcribe_time', sa.Float(), nullable=True),
    sa.Column('translate_time', sa.Float(), nullable=True),
    sa.Column('audio_length', sa.Float(), nullable=False),
    sa.Column('rtf', sa.Float(), nullable=True),
    sa.Column('audio_tags', sa.String(length=100), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=True),
    sa.Column('stt_data', sa.UnicodeText(), nullable=False),
    sa.Column('audio_info', sa.UnicodeText(), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('lm_time', sa.DateTime(), nullable=False),
    sa.Column('lm_user', sa.String(length=50), nullable=False),
    sa.Column('create_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f(f'ix_{table_prefix}Babelon_whisper_API_uid'), f'{table_prefix}Babelon_whisper_API', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    table_prefix = context.config.attributes.get("prefix", "mycopilot")
    if not table_prefix.endswith("_"):
        table_prefix += "_"
        
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f(f'ix_{table_prefix}Babelon_whisper_API_uid'), table_name=f'{table_prefix}Babelon_whisper_API')
    op.drop_table(f'{table_prefix}Babelon_whisper_API')
    # ### end Alembic commands ###
