"""new table remove websocket info and add this to post function

Revision ID: beeeea1b9c7f
Revises: a0786ca0e0b5
Create Date: 2025-12-12 13:28:01.267085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beeeea1b9c7f'
down_revision: Union[str, Sequence[str], None] = 'a0786ca0e0b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
